spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4jsecret
  #data:
    #neo4j:
      #database: my-database
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      dynamodb:
        enabled: true
  docker:
    compose:
      enabled: true
      file: ./four-hr-crawler-app/compose.yaml

persistence:
  crawl-state-time-to-live: 7d
